# Generated by Django 5.1.5 on 2025-01-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('segment_sizes', models.JSONField()),
                ('blade_width', models.FloatField()),
                ('obj_value', models.FloatField()),
                ('solution', models.JSONField()),
            ],
        ),
    ]
