# Generated by Django 5.1.5 on 2026-02-06 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã OTP mà user cần nhập khi đăng nhập', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Bật/tắt yêu cầu OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mã OTP',
                'verbose_name_plural': 'Mã OTP',
            },
        ),
    ]
